CC = gcc
CFLAG = -Wall -Wextra -g -o

.PHONY: clean
.PHONY: all

all: 1 2

1: 
	$(CC) main2_1.c -o main2_1

1: 
	$(CC) main2_2.c -o main2_2

git:
	git add -A
	git commit -m "$m"
	git push

clean:
	rm -f *.o *.so main2_1 main2_2